### ISSUE TITLE
angular-animate doesn't work

### ISSUE THREAD

**Issue by humbertn** [angular/angular-phonecat#259]
### Error message:
> TypeError: Cannot read property '' of undefined
>     at lookup (angular-animate.js:619)
>     at animationRunner (angular-animate.js:683)
>     at performAnimation (angular-animate.js:1286)
>     at angular-animate.js:961
>     at angular-animate.js:541
>     at Scope.$digest (angular.js:15717)
>     at Scope.$apply (angular.js:15935)
>     at done (angular.js:10356)
>     at completeRequest (angular.js:10528)
>     at XMLHttpRequest.requestLoaded (angular.js:10469)

### Solution:

- Remove angular-anima.js import from index.html
- Remove 'phonecatAnimations' injection in app.js

**Comment by matiishyn** [comment]
have same problem. It happened for me after updating Angular from 1.3.x to 1.4.1

**Comment by sergiy-talashko** [comment]
+1 
After updating to 1.4.1

**Comment by matiishyn** [comment]
fixed it updating angular-animate

**Comment by HaythemJ** [comment]
I am using angular-1.4.2 and I am using the lastest version of angular-animate on Github and it still not working.
